version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "3000:5000"
    volumes:
      - ./frontend:/app