version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the backend folder
    ports:
      - "80:80"  # Expose backend port 80
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/eventLogging
    networks:
      - event-logging-network

  frontend:
    build:
      context: ./frontend  # Path to the frontend folder
    ports:
      - "5000:5000"  # Expose frontend port 5000
    depends_on:
      - backend
    networks:
      - event-logging-network

networks:
  event-logging-network:
    driver: bridge
