version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # This should point to the correct Dockerfile in ./backend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # This should point to the correct Dockerfile in ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
